## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 50

# safelist
branches:
  only:
  - develop

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)

matrix:
  allow_failures:
    - julia: 0.6.0
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
     update: true
     packages:
     - gfortran
     - gcc

before_install:
#- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
#     /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; brew upgrade;
#  fi

#install: 
#   if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
#    ./deps/julia-make.sh;
#   fi

## uncomment the following lines to override the default test script
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
#     julia -e 'Pkg.add("MAT")'; 
#  elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
#     brew tap homebrew/science; brew install hdf5; julia -e 'Pkg.add("HDF5"); Pkg.add("MAT")';
#  fi
- julia -e 'Pkg.clone(pwd()); Pkg.build("AMA"); Pkg.test("AMA"; coverage=true)'

after_success:
- if [ "$TRAVIS_JULIA_VERSION" != "nightly" ]; then
      julia -e 'cd(Pkg.dir("AMA")); using Coverage; amaRes = process_folder(); Coveralls.submit(amaRes); Codecov.submit(amaRes)';
   fi
