## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
- linux
- osx
julia:
- 0.6.0
- nightly
notifications:
email: false
git:
depth: 99999999
# safelist
branches:
only:
- develop

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)

#matrix:
#  allow_failures:
#    - julia: 0.6.0
#    - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
     update: true
     packages:
     - gfortran

#install:
#  -

before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi
#  - if [ $TRAVIS_OS_NAME = linux ]; then apt-get update; fi
   - if [ $TRAVIS_OS_NAME = osx ]; brew install hdf5; Pkg.build("HDF5"); fi

## uncomment the following lines to override the default test script
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e 'Pkg.clone(pwd())'
- julia -e 'Pkg.build("AMA")'
- julia -e 'Pkg.test("AMA"; coverage=true)'

after_success:
- if [ "$TRAVIS_JULIA_VERSION" != "nightly" ]; then
      julia -e 'cd(Pkg.dir("AMA")); using Coverage; amaRes = process_folder(); Coveralls.submit(amaRes); Codecov.submit(amaRes)';
   fi
